# Generated by Django 5.2.17 on 2026-09-15 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_stay'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stay',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='stay',
            name='one_active_stay_per_resident',
        ),
        migrations.AddField(
            model_name='stay',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stay',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('reserved', 'Reserved'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='awaiting_payment', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='stay',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['awaiting_payment', 'reserved', 'checked_in'])), fields=('resident',), name='one_active_stay_per_resident'),
        ),
    ]
