# Generated by Django 5.2.17 on 2026-09-13 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0002_stay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('visit_date', models.DateField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('checked_in', 'Checked in'), ('checked_out', 'Checked out'), ('cancelled', 'Cancelled')], default='expected', max_length=20)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='accommodation.stay')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
