# Generated by Django 5.2.17 on 2026-09-13 18:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0002_stay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_charges', to=settings.AUTH_USER_MODEL)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='accommodation.stay')),
            ],
            options={
                'ordering': ['-billing_month', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('stay', 'billing_month'), name='one_rent_charge_per_stay_month')],
            },
        ),
    ]
