# Generated by Django 5.2.17 on 2026-09-15 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_alter_stay_options_and_more'),
        ('payments', '0002_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='is_initial_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(condition=models.Q(('is_initial_rent', True)), fields=('stay',), name='one_initial_rent_charge_per_stay'),
        ),
    ]
