# Generated by Django 5.2.17 on 2026-09-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_mpesapaymentattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
